### ISSUE TITLE
Max speed for different vehicles

### ISSUE THREAD

**Issue by frostypxrp** [TKLeuPT/SpeedLimiter#1]
Hey Im trying to make it so some cars have a max speed and some don't is there any way to do that?

**Comment by TKLeuPT** [comment]
Hey, this script works with categories.
It is possible to set different speeds for different categories.

In order to customize each car it would have to have a list with the car ids and limit by id.
You can achieve this with some modifications.

**Comment by frostypxrp** [comment]
okay thanks, also how would I change what categories I want to go different speeds or is it just all

**Comment by TKLeuPT** [comment]
I will make it so you can change the speed by category :)

**Comment by frostypxrp** [comment]
thank you!

**Comment by TKLeuPT** [comment]
Hey @frostypxrp I just uploaded the modified script 😄 
This new version allows to choose between both options
Feel free to hit me up if you find any bugs
Enjoy!

Regards,
Tekay
