### ISSUE TITLE
configure categories

### ISSUE THREAD

**Issue by zairus31** [TKLeuPT/SpeedLimiter#2]
Good job with the speed limit but I don't understand how to limit them by categories?
I would like this not to apply to ships, planes

**Comment by TKLeuPT** [comment]
Hey @zairus31 , it should not lock planes.
I can setup a config file by category, currently the speed limit is to all vehicle categories except planes and helicopters.

**Comment by zairus31** [comment]
It would be great to have a configuration file per category, you are doing a beautiful job

**Comment by TKLeuPT** [comment]
Hello @zairus31 I will be uploading in a bit the script with this modification :)

**Comment by TKLeuPT** [comment]
Hey @zairus31  I just uploaded the modified script 😄 
This new version allows to choose between both options
Feel free to hit me up if you find any bugs
Enjoy!

Regards,
Tekay
