### ISSUE TITLE
if Speed limit is too high it doesn't work.

### ISSUE THREAD

**Issue by frostypxrp** [TKLeuPT/SpeedLimiter#3]
Hey man, Love the script. I'm using km/h and anytime I make the max speed over 200km/h it just doesn't lock the speed.

So like if I have it locked at 200km/h it locks there
But lets say I have it locked at 205 or above it just doesn't lock it anymore and the vehicles just go as fast as they can go

**Comment by TKLeuPT** [comment]
Hey @frostypxrp!
Maybe this was because of late night code 🤣
I will have a look on this today as soon as I get home from work and will let you know about the fix so you can update it 🙂

Regards
TK

**Comment by frostypxrp** [comment]
Thank you very much!

**Comment by TKLeuPT** [comment]
Hey @frostypxrp, just updated the script!

Regards,
TK
