### ISSUE TITLE
Speed limit bug

### ISSUE THREAD

**Issue by florijanftw** [TKLeuPT/SpeedLimiter#5]
Basicly the bug happens when you spawn another car it stops working
Video: https://streamable.com/o441tn

**Comment by DoppelApfel** [comment]
+1

**Comment by TKLeuPT** [comment]
Hey Guys!
Sorry for not answering, I've been a bit busy 😄 

That is happening because you spawn inside the car.

I will be fixing this 😄

**Comment by TKLeuPT** [comment]
@florijanftw @DoppelApfel Just released a new version with a fix :)
